### ISSUE TITLE
API is not very friendly

### ISSUE THREAD

**Issue by imurluck** [yalue/elf_reader#1]
it's a very useful library, but the API didn't feel very friendly during my use.
such as `elf.DynamicEntries(intex uint16)`, first i need to find the index of 
dynamic section, but I think the library can get the index by itself.

additional, can provides some other APIs, such as get needed libraries of dynamic section.

thanks your lib.

**Comment by yalue** [comment]
Hi, and thank you for the comments.  The reason I don't (currently) have an API for functionality like "get the dynamic section" is that a file may technically contain more than one "dynamic" section (i.e., contain more than one section named `.dynamic` or have more than one section with specifying a type of `6` in its header).  Perhaps I could add a simple function that just returns the first section with a type of `6`, which should work for any sane Linux ELF, at least.... In any case, I'm still thinking about it.  In the meantime, the `elfFile.IsDynamicSection(<section index>)` function is already defined in the interface shared by both 64- and 32-bit ELF files, so you can use that to search for the correct index.

As for getting the library dependencies listed in the dynamic section, I do intend to add this eventually.  However, working on this library is rarely a priority for me (I generally add functionality only as I need it for my own work), so if you already have an implementation, I'd be happy to look at a PR!
